<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>12</LangVersion>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<PropertyGroup>
		<AssemblyVersion>1.0.0.2</AssemblyVersion>
		<FileVersion>$(AssemblyVersion)</FileVersion>
	</PropertyGroup>

	<PropertyGroup>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Description>Whatever, as title says.</Description>
		<Title>Whatever</Title>
		<RepositoryUrl>https://github.com/aybe/Whatever</RepositoryUrl>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<IncludeSymbols>True</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
		<Version>$(AssemblyVersion)</Version>
	</PropertyGroup>

	<PropertyGroup>
		<EnableNETAnalyzers>True</EnableNETAnalyzers>
		<AnalysisLevel>latest-all</AnalysisLevel>
		<EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
	</PropertyGroup>

	<ItemGroup>
	  <None Include="Extensions\ConvertExtensions.g.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>ConvertExtensions.tt</DependentUpon>
	  </None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="JetBrains.Annotations" Version="2023.3.0" />
		<PackageReference Include="Microsoft.Extensions.ObjectPool" Version="8.0.7" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="Extensions\ConvertExtensions.tt">
	    <Generator>TextTemplatingFileGenerator</Generator>
	    <LastGenOutput>ConvertExtensions.g.cs</LastGenOutput>
	  </None>
	</ItemGroup>

	<ItemGroup>
	  <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Extensions\ConvertExtensions.g.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>ConvertExtensions.tt</DependentUpon>
	  </Compile>
	</ItemGroup>

</Project>